### ISSUE TITLE
README still refers to sumArray instead of new test for sumNumbers

### ISSUE THREAD

**Issue by jocnjr** [ironhack-labs/lab-javascript-functions-and-arrays#1525]
Hey guys, 

It seems that the tests have recently changed from sumArray to sumNumbers, but the README file still refers to sumArray.

Thanks.

JOC

**Comment by sandrabosk** [comment]
@jocnjr Thank you for catching the error. The change in the function name slipped through when we updated the tests. 

Closing the issue - fixed.
